/**
 * Notification Push/In-App Configuration
 * 
 * This file contains the mapping of notification types to their delivery method
 * Based on the client masterlist specification
 * 
 * Usage:
 * import { isPushNotification } from './notificationConfig';
 * const shouldPush = isPushNotification('MATCH_REMINDER');
 */

import { NOTIFICATION_TYPES } from '../types/notificationTypes';

/**
 * Set of notification types that should be sent as Push notifications
 * All others are In-App only
 */
export const PUSH_NOTIFICATION_TYPES = new Set([
  // Account & System - Push (9)
  NOTIFICATION_TYPES.FIRST_MATCH_COMPLETED, // NOTIF-005
  NOTIFICATION_TYPES.MATCHES_PLAYED_MILESTONE, // NOTIF-006
  NOTIFICATION_TYPES.FIRST_LEAGUE_COMPLETED, // NOTIF-007
  NOTIFICATION_TYPES.LEAGUES_COMPLETED_MILESTONE, // NOTIF-008
  NOTIFICATION_TYPES.PERFECT_ATTENDANCE, // NOTIF-011
  NOTIFICATION_TYPES.MULTI_LEAGUE_PLAYER, // NOTIF-012
  NOTIFICATION_TYPES.STREAK_AT_RISK, // NOTIF-013
  NOTIFICATION_TYPES.NEW_WEEKLY_STREAK, // NOTIF-014
  NOTIFICATION_TYPES.APP_UPDATE_AVAILABLE, // NOTIF-015
  NOTIFICATION_TYPES.SYSTEM_MAINTENANCE, // NOTIF-016
  NOTIFICATION_TYPES.MAINTENANCE_COMPLETE, // NOTIF-017

  // Match Management - Push (31)
  NOTIFICATION_TYPES.FRIENDLY_MATCH_JOIN_REQUEST, // NOTIF-070
  NOTIFICATION_TYPES.FRIENDLY_MATCH_PLAYER_JOINED, // NOTIF-071
  NOTIFICATION_TYPES.FRIENDLY_MATCH_REQUEST_ACCEPTED, // NOTIF-072
  NOTIFICATION_TYPES.FRIENDLY_MATCH_REQUEST_DECLINED, // NOTIF-073
  NOTIFICATION_TYPES.MATCH_SCHEDULED, // NOTIF-075, 076, 077 (League matches)
  NOTIFICATION_TYPES.MATCH_CANCELLED, // NOTIF-078, 079
  NOTIFICATION_TYPES.PLAYER_LEFT_FRIENDLY_MATCH, // NOTIF-080
  NOTIFICATION_TYPES.FRIENDLY_MATCH_DETAILS_CHANGED, // NOTIF-082
  NOTIFICATION_TYPES.MATCH_RESCHEDULE_REQUEST, // NOTIF-083
  NOTIFICATION_TYPES.MATCH_RESCHEDULE_ACCEPTED, // NOTIF-084
  NOTIFICATION_TYPES.MATCH_RESCHEDULE_DECLINED, // NOTIF-085
  NOTIFICATION_TYPES.MATCH_REMINDER, // NOTIF-086, 087, 088
  NOTIFICATION_TYPES.MATCH_WALKOVER_WON, // NOTIF-089
  NOTIFICATION_TYPES.MATCH_WALKOVER_LOST, // NOTIF-090
  NOTIFICATION_TYPES.NO_SHOW_STRIKE_WARNING, // NOTIF-091
  NOTIFICATION_TYPES.OPPONENT_CLAIMS_NO_SHOW, // NOTIF-092
  NOTIFICATION_TYPES.SCORE_SUBMISSION_REMINDER, // NOTIF-094
  NOTIFICATION_TYPES.SCORE_DISPUTE_ALERT, // NOTIF-095
  NOTIFICATION_TYPES.MATCH_RESULT_CONFIRMED, // NOTIF-096
  NOTIFICATION_TYPES.OPPONENT_SUBMITTED_SCORE, // NOTIF-097
  NOTIFICATION_TYPES.PENDING_SCORE_SUBMISSION, // NOTIF-098
  NOTIFICATION_TYPES.PENDING_SCORE_CONFIRMATION, // NOTIF-099
  NOTIFICATION_TYPES.SCORE_AUTO_CONFIRMED, // NOTIF-100
  NOTIFICATION_TYPES.FORFEIT_DISCIPLINARY, // NOTIF-101
  NOTIFICATION_TYPES.WINNING_STREAK, // NOTIF-035
  NOTIFICATION_TYPES.SCHEDULE_MATCH_SOON, // NOTIF-036

  // League Lifecycle - Push (22)
  NOTIFICATION_TYPES.SEASON_REGISTRATION_OPEN, // NOTIF-057, 058
  NOTIFICATION_TYPES.REGISTRATION_CLOSING_3_DAYS, // NOTIF-059
  NOTIFICATION_TYPES.REGISTRATION_CLOSING_24_HOURS, // NOTIF-060
  NOTIFICATION_TYPES.LEAGUE_STARTING_3_DAYS, // NOTIF-061
  NOTIFICATION_TYPES.LEAGUE_STARTS_TOMORROW, // NOTIF-062
  NOTIFICATION_TYPES.LEAGUE_STARTED_WELCOME, // NOTIF-063
  NOTIFICATION_TYPES.DIVISION_REBALANCED, // NOTIF-033
  NOTIFICATION_TYPES.DIVISION_UPDATE_NEW_PLAYER, // NOTIF-034
  NOTIFICATION_TYPES.EARLY_SEASON_NUDGE, // NOTIF-037
  NOTIFICATION_TYPES.MID_SEASON_UPDATE, // NOTIF-038
  NOTIFICATION_TYPES.LATE_SEASON_NUDGE, // NOTIF-039
  NOTIFICATION_TYPES.INACTIVITY_WARNING, // NOTIF-040, 041, 042
  NOTIFICATION_TYPES.INACTIVITY_DEADLINE_7_DAYS, // NOTIF-043
  NOTIFICATION_TYPES.INACTIVITY_DEADLINE_3_DAYS, // NOTIF-044
  NOTIFICATION_TYPES.FINAL_WEEK_ALERT, // NOTIF-046
  NOTIFICATION_TYPES.LAST_MATCH_DEADLINE_48H, // NOTIF-047
  NOTIFICATION_TYPES.SEASON_ENDED, // NOTIF-048
  NOTIFICATION_TYPES.LEAGUE_WINNER, // NOTIF-049
  NOTIFICATION_TYPES.TOP_3_FINISH, // NOTIF-050
  NOTIFICATION_TYPES.LEAGUE_COMPLETE_BANNER, // NOTIF-051
  NOTIFICATION_TYPES.SEASON_CANCELLED, // NOTIF-053
  NOTIFICATION_TYPES.LEAGUE_EXTENDED, // NOTIF-054
  NOTIFICATION_TYPES.LEAGUE_SHORTENED, // NOTIF-055
  NOTIFICATION_TYPES.EMERGENCY_LEAGUE_UPDATE, // NOTIF-056
  NOTIFICATION_TYPES.PAYMENT_FAILED, // NOTIF-066
  NOTIFICATION_TYPES.WITHDRAWAL_REQUEST_APPROVED, // NOTIF-067
  NOTIFICATION_TYPES.REFUND_PROCESSED, // NOTIF-068

  // Rating & Ranking - Push (8)
  NOTIFICATION_TYPES.MOVED_UP_IN_STANDINGS, // NOTIF-110
  NOTIFICATION_TYPES.ENTERED_TOP_10, // NOTIF-111
  NOTIFICATION_TYPES.ENTERED_TOP_3, // NOTIF-112
  NOTIFICATION_TYPES.LEAGUE_LEADER, // NOTIF-113
  NOTIFICATION_TYPES.DMR_INCREASED, // NOTIF-115
  NOTIFICATION_TYPES.MONTHLY_DMR_RECAP, // NOTIF-116
  NOTIFICATION_TYPES.PERSONAL_BEST_RATING, // NOTIF-117
  NOTIFICATION_TYPES.RATING_MILESTONE, // NOTIF-118

  // Doubles League - Push (11)
  NOTIFICATION_TYPES.PAIR_REQUEST_RECEIVED, // NOTIF-021
  NOTIFICATION_TYPES.PAIR_REQUEST_ACCEPTED, // NOTIF-022, 023
  NOTIFICATION_TYPES.PAIR_REQUEST_DECLINED, // NOTIF-024
  NOTIFICATION_TYPES.TEAM_REGISTRATION_REMINDER_2H, // NOTIF-026
  NOTIFICATION_TYPES.TEAM_REGISTRATION_REMINDER_24H, // NOTIF-027
  NOTIFICATION_TYPES.REGISTRATION_DEADLINE_CAPTAIN, // NOTIF-028
  NOTIFICATION_TYPES.WAITING_FOR_CAPTAIN, // NOTIF-029
  NOTIFICATION_TYPES.REGISTRATION_DEADLINE_PARTNER, // NOTIF-030
  NOTIFICATION_TYPES.DOUBLES_TEAM_REGISTERED_CAPTAIN, // NOTIF-031
  NOTIFICATION_TYPES.DOUBLES_TEAM_REGISTERED_PARTNER, // NOTIF-032

  // Social & Community - Push (4)
  NOTIFICATION_TYPES.FRIEND_ACTIVITY_SCORECARD, // NOTIF-119
  NOTIFICATION_TYPES.FRIEND_ACTIVITY_POST, // NOTIF-120
  NOTIFICATION_TYPES.NEW_MESSAGE, // NOTIF-123, 125 (Match Chat, Group Chat)
  NOTIFICATION_TYPES.FRIEND_REQUEST, // NOTIF-124

  // Promotional - Push (8)
  NOTIFICATION_TYPES.NEXT_SEASON_OPENING_SOON, // NOTIF-102
  NOTIFICATION_TYPES.SPONSORED_LEAGUE_ANNOUNCEMENT, // NOTIF-103
  NOTIFICATION_TYPES.REFERRAL_BONUS_AVAILABLE, // NOTIF-104
  NOTIFICATION_TYPES.INACTIVE_PLAYER_14_DAYS, // NOTIF-105
  NOTIFICATION_TYPES.INACTIVE_PLAYER_30_DAYS, // NOTIF-106
  NOTIFICATION_TYPES.LEAGUE_BETWEEN_BREAKS, // NOTIF-107
  NOTIFICATION_TYPES.INCOMPLETE_REGISTRATION, // NOTIF-108
  NOTIFICATION_TYPES.VENUE_SPECIAL_OFFER, // NOTIF-109

  // Special Circumstances - Push (3)
  NOTIFICATION_TYPES.DISPUTE_RESOLUTION_REQUIRED, // NOTIF-128
  NOTIFICATION_TYPES.DISPUTE_RESOLVED, // NOTIF-129
  NOTIFICATION_TYPES.CODE_OF_CONDUCT_WARNING, // NOTIF-130
]);

/**
 * Check if a notification type should be sent as Push notification
 * @param type Notification type constant
 * @returns true if should be Push, false if In-App only
 */
export function isPushNotification(type: string): boolean {
  return PUSH_NOTIFICATION_TYPES.has(type);
}

/**
 * Get delivery method for notification type
 * @param type Notification type constant
 * @returns 'push' or 'in-app'
 */
export function getNotificationDeliveryMethod(type: string): 'push' | 'in-app' {
  return isPushNotification(type) ? 'push' : 'in-app';
}

/**
 * In-App only notification types (for reference)
 */
export const IN_APP_NOTIFICATION_TYPES = new Set([
  // Account & System - In-App (6)
  NOTIFICATION_TYPES.WELCOME_TO_DEUCE, // NOTIF-001
  NOTIFICATION_TYPES.PROFILE_INCOMPLETE_REMINDER, // NOTIF-002
  NOTIFICATION_TYPES.PROFILE_PHOTO_MISSING, // NOTIF-003
  NOTIFICATION_TYPES.PROFILE_VERIFICATION_NEEDED, // NOTIF-004
  NOTIFICATION_TYPES.ACHIEVEMENT_UNLOCKED, // NOTIF-009
  NOTIFICATION_TYPES.TOS_UPDATED, // NOTIF-018

  // Match Management - In-App (4)
  NOTIFICATION_TYPES.FRIENDLY_MATCH_POSTED, // NOTIF-069
  NOTIFICATION_TYPES.SCHEDULING_CONFLICT_DETECTED, // NOTIF-081
  NOTIFICATION_TYPES.HEAD_TO_HEAD_HISTORY, // NOTIF-093

  // League Lifecycle - In-App (4)
  NOTIFICATION_TYPES.SEASON_REGISTRATION_CONFIRMED, // NOTIF-064
  NOTIFICATION_TYPES.PAYMENT_CONFIRMED, // NOTIF-065
  NOTIFICATION_TYPES.MATCHES_REMAINING, // NOTIF-045
  NOTIFICATION_TYPES.LEAGUE_PERFORMANCE_SUMMARY, // NOTIF-052

  // Doubles League - In-App (2)
  NOTIFICATION_TYPES.PARTNER_REQUEST_SENT, // NOTIF-020
  NOTIFICATION_TYPES.PAIR_REQUEST_REJECTED, // NOTIF-025 (duplicate of declined-partner)

  // Social & Community - In-App (3)
  NOTIFICATION_TYPES.SIMILAR_SKILL_PLAYER_NEARBY, // NOTIF-121
  NOTIFICATION_TYPES.SHARE_SCORECARD_PROMPT, // NOTIF-122

  // Rating & Ranking - In-App (1)
  NOTIFICATION_TYPES.WEEKLY_RANKING_UPDATE, // NOTIF-114

  // Special Circumstances - In-App (2)
  NOTIFICATION_TYPES.DISPUTE_SUBMITTED, // NOTIF-131
  NOTIFICATION_TYPES.OPPONENT_REPORTED_ISSUE, // NOTIF-132
]);

/**
 * Priority levels for notifications (affects badge display and persistence)
 */
export enum NotificationPriority {
  CRITICAL = 'CRITICAL', // Red dot, persistent
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
}

/**
 * Get priority level for notification type
 */
export function getNotificationPriority(type: string): NotificationPriority {
  const criticalTypes = [
    NOTIFICATION_TYPES.PROFILE_VERIFICATION_NEEDED,
    NOTIFICATION_TYPES.PAYMENT_FAILED,
    NOTIFICATION_TYPES.INACTIVITY_DEADLINE_7_DAYS,
    NOTIFICATION_TYPES.INACTIVITY_DEADLINE_3_DAYS,
    NOTIFICATION_TYPES.REGISTRATION_DEADLINE_CAPTAIN,
    NOTIFICATION_TYPES.REGISTRATION_DEADLINE_PARTNER,
    NOTIFICATION_TYPES.CODE_OF_CONDUCT_WARNING,
    NOTIFICATION_TYPES.EMERGENCY_LEAGUE_UPDATE,
    NOTIFICATION_TYPES.LEAGUE_SHORTENED,
  ];

  const highTypes = [
    NOTIFICATION_TYPES.MATCH_SCHEDULED,
    NOTIFICATION_TYPES.PAIR_REQUEST_RECEIVED,
    NOTIFICATION_TYPES.TEAM_REGISTRATION_REMINDER_2H,
    NOTIFICATION_TYPES.TEAM_REGISTRATION_REMINDER_24H,
    NOTIFICATION_TYPES.SYSTEM_MAINTENANCE,
    NOTIFICATION_TYPES.MATCH_REMINDER,
    NOTIFICATION_TYPES.NO_SHOW_STRIKE_WARNING,
  ];

  if (criticalTypes.includes(type)) return NotificationPriority.CRITICAL;
  if (highTypes.includes(type)) return NotificationPriority.HIGH;
  
  // Default to MEDIUM for most notifications
  return NotificationPriority.MEDIUM;
}
