import { NotificationCategory } from '@prisma/client';


export type NotificationType = string;

// Common notification types as constants for consistency
export const NOTIFICATION_TYPES = {
  
  // Division notifications
  DIVISION_ASSIGNED: 'DIVISION_ASSIGNED',
  DIVISION_TRANSFERRED: 'DIVISION_TRANSFERRED',
  DIVISION_REMOVED: 'DIVISION_REMOVED',
  DIVISION_CREATED: 'DIVISION_CREATED',
  
  // Chat notifications
  GROUP_CHAT_ADDED: 'GROUP_CHAT_ADDED',
  NEW_MESSAGE: 'NEW_MESSAGE',
  UNREAD_MESSAGES: 'UNREAD_MESSAGES',
  
  // Match notifications
  MATCH_SCHEDULED: 'MATCH_SCHEDULED',
  MATCH_REMINDER: 'MATCH_REMINDER',
  MATCH_RESULT: 'MATCH_RESULT',
  MATCH_CANCELLED: 'MATCH_CANCELLED',
  
  // Season notifications
  SEASON_REGISTRATION_CONFIRMED: 'SEASON_REGISTRATION_CONFIRMED',
  NEW_SEASON_ANNOUNCEMENT: ' NEW_SEASON_ANNOUNCEMENT',
  SEASON_STARTING_SOON: 'SEASON_STARTING_SOON',
  SEASON_ENDED: 'SEASON_ENDED',
  SEASON_CANCELLED: 'SEASON_CANCELLED',
  
  // Pairing notifications
  PAIR_REQUEST_RECEIVED: 'PAIR_REQUEST_RECEIVED',
  PAIR_REQUEST_ACCEPTED: 'PAIR_REQUEST_ACCEPTED',
  PAIR_REQUEST_REJECTED: 'PAIR_REQUEST_REJECTED',
  PARTNERSHIP_DISSOLVED: 'PARTNERSHIP_DISSOLVED',
  
  // Payment notifications
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_REMINDER: 'PAYMENT_REMINDER',
  
  // Achievement notifications
  ACHIEVEMENT_UNLOCKED: 'ACHIEVEMENT_UNLOCKED',
  LEVEL_UP: 'LEVEL_UP',
  RANKING_UPDATE: 'RANKING_UPDATE',
  
  // Withdrawal notifications
  WITHDRAWAL_REQUEST_RECEIVED: 'WITHDRAWAL_REQUEST_RECEIVED',
  WITHDRAWAL_REQUEST_APPROVED: 'WITHDRAWAL_REQUEST_APPROVED',
  WITHDRAWAL_REQUEST_REJECTED: 'WITHDRAWAL_REQUEST_REJECTED',
  
  // Admin notifications
  ADMIN_MESSAGE: 'ADMIN_MESSAGE',
  SYSTEM_MAINTENANCE: 'SYSTEM_MAINTENANCE',
  NEW_FEATURE: 'NEW_FEATURE',
  
  // General reminders
  MATCH_UPCOMING: 'MATCH_UPCOMING',
  REGISTRATION_DEADLINE: 'REGISTRATION_DEADLINE',
  PAYMENT_DUE: 'PAYMENT_DUE',
  
  // Tournament notifications
  TOURNAMENT_INVITATION: 'TOURNAMENT_INVITATION',
  TOURNAMENT_RESULT: 'TOURNAMENT_RESULT',

  // Inactivity notifications
  INACTIVITY_WARNING: 'INACTIVITY_WARNING',
  STATUS_CHANGED_TO_INACTIVE: 'STATUS_CHANGED_TO_INACTIVE',
  REACTIVATED: 'REACTIVATED',

  // Rating notifications
  RATING_UPDATE: 'RATING_UPDATE',
  RATING_ADJUSTED: 'RATING_ADJUSTED',

  // Partner/Opponent change notifications
  OPPONENT_CHANGED: 'OPPONENT_CHANGED',
  PARTNER_CHANGED: 'PARTNER_CHANGED',

  // Season registration notifications
  SEASON_REGISTRATION_OPEN: 'SEASON_REGISTRATION_OPEN',

  // Admin-specific notifications
  ADMIN_WITHDRAWAL_REQUEST: 'ADMIN_WITHDRAWAL_REQUEST',
  ADMIN_DISPUTE_SUBMITTED: 'ADMIN_DISPUTE_SUBMITTED',
  ADMIN_TEAM_CHANGE_REQUEST: 'ADMIN_TEAM_CHANGE_REQUEST',
  ADMIN_SEASON_JOIN_REQUEST: 'ADMIN_SEASON_JOIN_REQUEST',
  ADMIN_PLAYER_REPORT: 'ADMIN_PLAYER_REPORT',

  // Account & System notifications
  WELCOME_TO_DEUCE: 'WELCOME_TO_DEUCE',
  PROFILE_INCOMPLETE_REMINDER: 'PROFILE_INCOMPLETE_REMINDER',
  PROFILE_PHOTO_MISSING: 'PROFILE_PHOTO_MISSING',
  PROFILE_VERIFICATION_NEEDED: 'PROFILE_VERIFICATION_NEEDED',
  FIRST_MATCH_COMPLETED: 'FIRST_MATCH_COMPLETED',
  MATCHES_PLAYED_MILESTONE: 'MATCHES_PLAYED_MILESTONE',
  FIRST_LEAGUE_COMPLETED: 'FIRST_LEAGUE_COMPLETED',
  LEAGUES_COMPLETED_MILESTONE: 'LEAGUES_COMPLETED_MILESTONE',
  PERFECT_ATTENDANCE: 'PERFECT_ATTENDANCE',
  MULTI_LEAGUE_PLAYER: 'MULTI_LEAGUE_PLAYER',
  NEW_WEEKLY_STREAK: 'NEW_WEEKLY_STREAK',
  STREAK_AT_RISK: 'STREAK_AT_RISK',
  APP_UPDATE_AVAILABLE: 'APP_UPDATE_AVAILABLE',
  MAINTENANCE_COMPLETE: 'MAINTENANCE_COMPLETE',
  TOS_UPDATED: 'TOS_UPDATED',

  // Doubles League notifications
  PARTNER_REQUEST_SENT: 'PARTNER_REQUEST_SENT',
  TEAM_REGISTRATION_REMINDER_2H: 'TEAM_REGISTRATION_REMINDER_2H',
  TEAM_REGISTRATION_REMINDER_24H: 'TEAM_REGISTRATION_REMINDER_24H',
  REGISTRATION_DEADLINE_CAPTAIN: 'REGISTRATION_DEADLINE_CAPTAIN',
  WAITING_FOR_CAPTAIN: 'WAITING_FOR_CAPTAIN',
  REGISTRATION_DEADLINE_PARTNER: 'REGISTRATION_DEADLINE_PARTNER',
  DOUBLES_TEAM_REGISTERED_CAPTAIN: 'DOUBLES_TEAM_REGISTERED_CAPTAIN',
  DOUBLES_TEAM_REGISTERED_PARTNER: 'DOUBLES_TEAM_REGISTERED_PARTNER',

  // League Lifecycle notifications
  DIVISION_UPDATE_NEW_PLAYER: 'DIVISION_UPDATE_NEW_PLAYER',
  WINNING_STREAK: 'WINNING_STREAK',
  SCHEDULE_MATCH_SOON: 'SCHEDULE_MATCH_SOON',
  LEAGUE_ANNOUNCEMENT: 'LEAGUE_ANNOUNCEMENT',
  EARLY_SEASON_NUDGE: 'EARLY_SEASON_NUDGE',
  MID_SEASON_UPDATE: 'MID_SEASON_UPDATE',
  LATE_SEASON_NUDGE: 'LATE_SEASON_NUDGE',
  INACTIVITY_DEADLINE_7_DAYS: 'INACTIVITY_DEADLINE_7_DAYS',
  INACTIVITY_DEADLINE_3_DAYS: 'INACTIVITY_DEADLINE_3_DAYS',
  MATCHES_REMAINING: 'MATCHES_REMAINING',
  FINAL_WEEK_ALERT: 'FINAL_WEEK_ALERT',
  LAST_MATCH_DEADLINE_48H: 'LAST_MATCH_DEADLINE_48H',
  LEAGUE_WINNER: 'LEAGUE_WINNER',
  TOP_3_FINISH: 'TOP_3_FINISH',
  LEAGUE_COMPLETE_BANNER: 'LEAGUE_COMPLETE_BANNER',
  LEAGUE_PERFORMANCE_SUMMARY: 'LEAGUE_PERFORMANCE_SUMMARY',
  LEAGUE_EXTENDED: 'LEAGUE_EXTENDED',
  LEAGUE_SHORTENED: 'LEAGUE_SHORTENED',
  EMERGENCY_LEAGUE_UPDATE: 'EMERGENCY_LEAGUE_UPDATE',
  REGISTRATION_CLOSING_3_DAYS: 'REGISTRATION_CLOSING_3_DAYS',
  REGISTRATION_CLOSING_24_HOURS: 'REGISTRATION_CLOSING_24_HOURS',
  LEAGUE_STARTING_3_DAYS: 'LEAGUE_STARTING_3_DAYS',
  LEAGUE_STARTS_TOMORROW: 'LEAGUE_STARTS_TOMORROW',
  LEAGUE_STARTED_WELCOME: 'LEAGUE_STARTED_WELCOME',
  REFUND_PROCESSED: 'REFUND_PROCESSED',

  // Match Management notifications
  FRIENDLY_MATCH_POSTED: 'FRIENDLY_MATCH_POSTED',
  FRIENDLY_MATCH_JOIN_REQUEST: 'FRIENDLY_MATCH_JOIN_REQUEST',
  FRIENDLY_MATCH_PLAYER_JOINED: 'FRIENDLY_MATCH_PLAYER_JOINED',
  FRIENDLY_MATCH_REQUEST_ACCEPTED: 'FRIENDLY_MATCH_REQUEST_ACCEPTED',
  FRIENDLY_MATCH_REQUEST_DECLINED: 'FRIENDLY_MATCH_REQUEST_DECLINED',

  // League Match notifications (NOTIF-075 to NOTIF-078)
  OPPONENT_POSTED_LEAGUE_MATCH: 'OPPONENT_POSTED_LEAGUE_MATCH',
  LEAGUE_MATCH_CONFIRMED_YOU_JOINED: 'LEAGUE_MATCH_CONFIRMED_YOU_JOINED',
  LEAGUE_MATCH_CONFIRMED_OPPONENT_JOINED: 'LEAGUE_MATCH_CONFIRMED_OPPONENT_JOINED',
  LEAGUE_MATCH_CANCELLED_BY_OPPONENT: 'LEAGUE_MATCH_CANCELLED_BY_OPPONENT',
  FRIENDLY_MATCH_CANCELLED: 'FRIENDLY_MATCH_CANCELLED',
  PLAYER_LEFT_FRIENDLY_MATCH: 'PLAYER_LEFT_FRIENDLY_MATCH',
  SCHEDULING_CONFLICT_DETECTED: 'SCHEDULING_CONFLICT_DETECTED',
  FRIENDLY_MATCH_DETAILS_CHANGED: 'FRIENDLY_MATCH_DETAILS_CHANGED',
  MATCH_RESCHEDULE_REQUEST: 'MATCH_RESCHEDULE_REQUEST',
  MATCH_RESCHEDULE_ACCEPTED: 'MATCH_RESCHEDULE_ACCEPTED',
  MATCH_RESCHEDULE_DECLINED: 'MATCH_RESCHEDULE_DECLINED',
  MATCH_WALKOVER_WON: 'MATCH_WALKOVER_WON',
  MATCH_WALKOVER_LOST: 'MATCH_WALKOVER_LOST',
  NO_SHOW_STRIKE_WARNING: 'NO_SHOW_STRIKE_WARNING',
  OPPONENT_CLAIMS_NO_SHOW: 'OPPONENT_CLAIMS_NO_SHOW',
  HEAD_TO_HEAD_HISTORY: 'HEAD_TO_HEAD_HISTORY',
  SCORE_SUBMISSION_REMINDER: 'SCORE_SUBMISSION_REMINDER',
  SCORE_DISPUTE_ALERT: 'SCORE_DISPUTE_ALERT',
  OPPONENT_SUBMITTED_SCORE: 'OPPONENT_SUBMITTED_SCORE',
  PENDING_SCORE_SUBMISSION: 'PENDING_SCORE_SUBMISSION',
  PENDING_SCORE_CONFIRMATION: 'PENDING_SCORE_CONFIRMATION',
  SCORE_AUTO_CONFIRMED: 'SCORE_AUTO_CONFIRMED',
  FORFEIT_DISCIPLINARY: 'FORFEIT_DISCIPLINARY',

  // Rating & Ranking notifications
  MOVED_UP_IN_STANDINGS: 'MOVED_UP_IN_STANDINGS',
  ENTERED_TOP_10: 'ENTERED_TOP_10',
  ENTERED_TOP_3: 'ENTERED_TOP_3',
  LEAGUE_LEADER: 'LEAGUE_LEADER',
  WEEKLY_RANKING_UPDATE: 'WEEKLY_RANKING_UPDATE',
  DMR_INCREASED: 'DMR_INCREASED',
  MONTHLY_DMR_RECAP: 'MONTHLY_DMR_RECAP',
  PERSONAL_BEST_RATING: 'PERSONAL_BEST_RATING',
  RATING_MILESTONE: 'RATING_MILESTONE',

  // Social & Community notifications
  FRIEND_ACTIVITY_SCORECARD: 'FRIEND_ACTIVITY_SCORECARD',
  FRIEND_ACTIVITY_POST: 'FRIEND_ACTIVITY_POST',
  SIMILAR_SKILL_PLAYER_NEARBY: 'SIMILAR_SKILL_PLAYER_NEARBY',
  SHARE_SCORECARD_PROMPT: 'SHARE_SCORECARD_PROMPT',
  FRIEND_REQUEST: 'FRIEND_REQUEST',

  // Promotional notifications
  NEXT_SEASON_OPENING_SOON: 'NEXT_SEASON_OPENING_SOON',
  SPONSORED_LEAGUE_ANNOUNCEMENT: 'SPONSORED_LEAGUE_ANNOUNCEMENT',
  REFERRAL_BONUS_AVAILABLE: 'REFERRAL_BONUS_AVAILABLE',
  INACTIVE_PLAYER_14_DAYS: 'INACTIVE_PLAYER_14_DAYS',
  INACTIVE_PLAYER_30_DAYS: 'INACTIVE_PLAYER_30_DAYS',
  LEAGUE_BETWEEN_BREAKS: 'LEAGUE_BETWEEN_BREAKS',
  INCOMPLETE_REGISTRATION: 'INCOMPLETE_REGISTRATION',
  VENUE_SPECIAL_OFFER: 'VENUE_SPECIAL_OFFER',

  // Special Circumstances notifications
  DISPUTE_RESOLUTION_REQUIRED: 'DISPUTE_RESOLUTION_REQUIRED',
  DISPUTE_RESOLVED: 'DISPUTE_RESOLVED',
  CODE_OF_CONDUCT_WARNING: 'CODE_OF_CONDUCT_WARNING',
  DISPUTE_SUBMITTED: 'DISPUTE_SUBMITTED',
  OPPONENT_REPORTED_ISSUE: 'OPPONENT_REPORTED_ISSUE',
} as const;

export interface NotificationPayload {
  type: NotificationType;
  category: NotificationCategory;
  title?: string | undefined;
  message: string;
  metadata?: Record<string, any> | undefined;
}


// FIX THIS LATER, CANNOT BE UNDEFINED 
export interface CreateNotificationData extends NotificationPayload {
  userIds: string | string[];
  seasonId?: string | undefined;
  divisionId?: string | undefined;
  matchId?: string | undefined;
  partnershipId?: string | undefined;
  threadId?: string | undefined;
  pairRequestId?: string | undefined;
  achievementId?: string | undefined; 
  withdrawalRequestId?: string | undefined;
}

export interface NotificationResult {
  id: string;
  title: string | undefined;
  message: string;
  category: NotificationCategory;
  type: string | undefined;
  read: boolean;
  archive: boolean;
  createdAt: Date;
  readAt: Date | undefined;
  metadata?: Record<string, any> | undefined;
}

export interface NotificationFilter {
  page?: number | undefined;
  limit?: number | undefined;
  unreadOnly?: boolean | undefined;
  archived?: boolean | undefined;
  category?: NotificationCategory | undefined;
  categories?: NotificationCategory[] | undefined;
  type?: NotificationType | undefined;
  types?: string[] | undefined; 
}

export interface PaginatedNotifications {
  notifications: NotificationResult[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
    hasMore: boolean;
  };
}

export interface NotificationStats {
  total: number;
  unread: number;
  archived: number;
  byCategory: Record<NotificationCategory, number>;
  byType: Record<NotificationType, number>;
}

// Helper function to get category from type
export function getCategoryForNotificationType(type: NotificationType): NotificationCategory {
  const categoryMap: Record<string, NotificationCategory> = {
    // Division types
    [NOTIFICATION_TYPES.DIVISION_ASSIGNED]: 'DIVISION',
    [NOTIFICATION_TYPES.DIVISION_TRANSFERRED]: 'DIVISION',
    [NOTIFICATION_TYPES.DIVISION_REMOVED]: 'DIVISION',
    [NOTIFICATION_TYPES.DIVISION_CREATED]: 'DIVISION',
    
    // Chat types
    [NOTIFICATION_TYPES.GROUP_CHAT_ADDED]: 'CHAT',
    [NOTIFICATION_TYPES.NEW_MESSAGE]: 'CHAT',
    
    // Match types
    [NOTIFICATION_TYPES.MATCH_SCHEDULED]: 'MATCH',
    [NOTIFICATION_TYPES.MATCH_REMINDER]: 'MATCH',
    [NOTIFICATION_TYPES.MATCH_RESULT]: 'MATCH',
    [NOTIFICATION_TYPES.MATCH_CANCELLED]: 'MATCH',
    [NOTIFICATION_TYPES.MATCH_UPCOMING]: 'MATCH',
    
    // Season types
    [NOTIFICATION_TYPES.SEASON_REGISTRATION_CONFIRMED]: 'SEASON',
    [NOTIFICATION_TYPES.SEASON_STARTING_SOON]: 'SEASON',
    [NOTIFICATION_TYPES.SEASON_ENDED]: 'SEASON',
    [NOTIFICATION_TYPES.SEASON_CANCELLED]: 'SEASON',
    [NOTIFICATION_TYPES.REGISTRATION_DEADLINE]: 'SEASON',
    
    // Payment types
    [NOTIFICATION_TYPES.PAYMENT_CONFIRMED]: 'PAYMENT',
    [NOTIFICATION_TYPES.PAYMENT_FAILED]: 'PAYMENT',
    [NOTIFICATION_TYPES.PAYMENT_REMINDER]: 'PAYMENT',
    [NOTIFICATION_TYPES.PAYMENT_DUE]: 'PAYMENT',
    
    // Admin types
    [NOTIFICATION_TYPES.ADMIN_MESSAGE]: 'ADMIN',
    [NOTIFICATION_TYPES.SYSTEM_MAINTENANCE]: 'ADMIN',
    [NOTIFICATION_TYPES.NEW_FEATURE]: 'ADMIN',
    
    // General types default to GENERAL
    [NOTIFICATION_TYPES.ACHIEVEMENT_UNLOCKED]: 'GENERAL',
    [NOTIFICATION_TYPES.LEVEL_UP]: 'GENERAL',
    [NOTIFICATION_TYPES.RANKING_UPDATE]: 'GENERAL',
    [NOTIFICATION_TYPES.WITHDRAWAL_REQUEST_RECEIVED]: 'GENERAL',
    [NOTIFICATION_TYPES.WITHDRAWAL_REQUEST_APPROVED]: 'GENERAL',
    [NOTIFICATION_TYPES.WITHDRAWAL_REQUEST_REJECTED]: 'GENERAL',
    [NOTIFICATION_TYPES.PAIR_REQUEST_RECEIVED]: 'GENERAL',
    [NOTIFICATION_TYPES.PAIR_REQUEST_ACCEPTED]: 'GENERAL',
    [NOTIFICATION_TYPES.PAIR_REQUEST_REJECTED]: 'GENERAL',
    [NOTIFICATION_TYPES.PARTNERSHIP_DISSOLVED]: 'GENERAL',
    [NOTIFICATION_TYPES.TOURNAMENT_INVITATION]: 'GENERAL',
    [NOTIFICATION_TYPES.TOURNAMENT_RESULT]: 'GENERAL',

    // Inactivity types
    [NOTIFICATION_TYPES.INACTIVITY_WARNING]: 'GENERAL',
    [NOTIFICATION_TYPES.STATUS_CHANGED_TO_INACTIVE]: 'GENERAL',
    [NOTIFICATION_TYPES.REACTIVATED]: 'GENERAL',

    // Rating types
    [NOTIFICATION_TYPES.RATING_UPDATE]: 'GENERAL',
    [NOTIFICATION_TYPES.RATING_ADJUSTED]: 'GENERAL',

    // Partner/Opponent change types
    [NOTIFICATION_TYPES.OPPONENT_CHANGED]: 'MATCH',
    [NOTIFICATION_TYPES.PARTNER_CHANGED]: 'MATCH',

    // Season registration
    [NOTIFICATION_TYPES.SEASON_REGISTRATION_OPEN]: 'SEASON',

    // Admin types
    [NOTIFICATION_TYPES.ADMIN_WITHDRAWAL_REQUEST]: 'ADMIN',
    [NOTIFICATION_TYPES.ADMIN_DISPUTE_SUBMITTED]: 'ADMIN',
    [NOTIFICATION_TYPES.ADMIN_TEAM_CHANGE_REQUEST]: 'ADMIN',
    [NOTIFICATION_TYPES.ADMIN_SEASON_JOIN_REQUEST]: 'ADMIN',
    [NOTIFICATION_TYPES.ADMIN_PLAYER_REPORT]: 'ADMIN',

    // Account & System
    [NOTIFICATION_TYPES.WELCOME_TO_DEUCE]: 'GENERAL',
    [NOTIFICATION_TYPES.PROFILE_INCOMPLETE_REMINDER]: 'GENERAL',
    [NOTIFICATION_TYPES.PROFILE_PHOTO_MISSING]: 'GENERAL',
    [NOTIFICATION_TYPES.PROFILE_VERIFICATION_NEEDED]: 'GENERAL',
    [NOTIFICATION_TYPES.FIRST_MATCH_COMPLETED]: 'GENERAL',
    [NOTIFICATION_TYPES.MATCHES_PLAYED_MILESTONE]: 'GENERAL',
    [NOTIFICATION_TYPES.FIRST_LEAGUE_COMPLETED]: 'LEAGUE',
    [NOTIFICATION_TYPES.LEAGUES_COMPLETED_MILESTONE]: 'LEAGUE',
    [NOTIFICATION_TYPES.PERFECT_ATTENDANCE]: 'LEAGUE',
    [NOTIFICATION_TYPES.MULTI_LEAGUE_PLAYER]: 'LEAGUE',
    [NOTIFICATION_TYPES.NEW_WEEKLY_STREAK]: 'GENERAL',
    [NOTIFICATION_TYPES.STREAK_AT_RISK]: 'GENERAL',
    [NOTIFICATION_TYPES.APP_UPDATE_AVAILABLE]: 'ADMIN',
    [NOTIFICATION_TYPES.MAINTENANCE_COMPLETE]: 'ADMIN',
    [NOTIFICATION_TYPES.TOS_UPDATED]: 'ADMIN',

    // Doubles League
    [NOTIFICATION_TYPES.PARTNER_REQUEST_SENT]: 'GENERAL',
    [NOTIFICATION_TYPES.TEAM_REGISTRATION_REMINDER_2H]: 'SEASON',
    [NOTIFICATION_TYPES.TEAM_REGISTRATION_REMINDER_24H]: 'SEASON',
    [NOTIFICATION_TYPES.REGISTRATION_DEADLINE_CAPTAIN]: 'SEASON',
    [NOTIFICATION_TYPES.WAITING_FOR_CAPTAIN]: 'SEASON',
    [NOTIFICATION_TYPES.REGISTRATION_DEADLINE_PARTNER]: 'SEASON',
    [NOTIFICATION_TYPES.DOUBLES_TEAM_REGISTERED_CAPTAIN]: 'SEASON',
    [NOTIFICATION_TYPES.DOUBLES_TEAM_REGISTERED_PARTNER]: 'SEASON',

    // League Lifecycle
    [NOTIFICATION_TYPES.DIVISION_UPDATE_NEW_PLAYER]: 'DIVISION',
    [NOTIFICATION_TYPES.WINNING_STREAK]: 'MATCH',
    [NOTIFICATION_TYPES.SCHEDULE_MATCH_SOON]: 'MATCH',
    [NOTIFICATION_TYPES.EARLY_SEASON_NUDGE]: 'SEASON',
    [NOTIFICATION_TYPES.MID_SEASON_UPDATE]: 'SEASON',
    [NOTIFICATION_TYPES.LATE_SEASON_NUDGE]: 'SEASON',
    [NOTIFICATION_TYPES.INACTIVITY_DEADLINE_7_DAYS]: 'GENERAL',
    [NOTIFICATION_TYPES.INACTIVITY_DEADLINE_3_DAYS]: 'GENERAL',
    [NOTIFICATION_TYPES.MATCHES_REMAINING]: 'MATCH',
    [NOTIFICATION_TYPES.FINAL_WEEK_ALERT]: 'SEASON',
    [NOTIFICATION_TYPES.LAST_MATCH_DEADLINE_48H]: 'MATCH',
    [NOTIFICATION_TYPES.LEAGUE_WINNER]: 'LEAGUE',
    [NOTIFICATION_TYPES.TOP_3_FINISH]: 'LEAGUE',
    [NOTIFICATION_TYPES.LEAGUE_COMPLETE_BANNER]: 'LEAGUE',
    [NOTIFICATION_TYPES.LEAGUE_PERFORMANCE_SUMMARY]: 'LEAGUE',
    [NOTIFICATION_TYPES.LEAGUE_EXTENDED]: 'LEAGUE',
    [NOTIFICATION_TYPES.LEAGUE_SHORTENED]: 'LEAGUE',
    [NOTIFICATION_TYPES.EMERGENCY_LEAGUE_UPDATE]: 'LEAGUE',
    [NOTIFICATION_TYPES.REGISTRATION_CLOSING_3_DAYS]: 'SEASON',
    [NOTIFICATION_TYPES.REGISTRATION_CLOSING_24_HOURS]: 'SEASON',
    [NOTIFICATION_TYPES.LEAGUE_STARTING_3_DAYS]: 'SEASON',
    [NOTIFICATION_TYPES.LEAGUE_STARTS_TOMORROW]: 'SEASON',
    [NOTIFICATION_TYPES.LEAGUE_STARTED_WELCOME]: 'SEASON',
    [NOTIFICATION_TYPES.REFUND_PROCESSED]: 'PAYMENT',

    // Match Management
    [NOTIFICATION_TYPES.FRIENDLY_MATCH_POSTED]: 'MATCH',
    [NOTIFICATION_TYPES.FRIENDLY_MATCH_JOIN_REQUEST]: 'MATCH',
    [NOTIFICATION_TYPES.FRIENDLY_MATCH_PLAYER_JOINED]: 'MATCH',
    [NOTIFICATION_TYPES.FRIENDLY_MATCH_REQUEST_ACCEPTED]: 'MATCH',
    [NOTIFICATION_TYPES.FRIENDLY_MATCH_REQUEST_DECLINED]: 'MATCH',
    [NOTIFICATION_TYPES.OPPONENT_POSTED_LEAGUE_MATCH]: 'MATCH',
    [NOTIFICATION_TYPES.LEAGUE_MATCH_CONFIRMED_YOU_JOINED]: 'MATCH',
    [NOTIFICATION_TYPES.LEAGUE_MATCH_CONFIRMED_OPPONENT_JOINED]: 'MATCH',
    [NOTIFICATION_TYPES.LEAGUE_MATCH_CANCELLED_BY_OPPONENT]: 'MATCH',
    [NOTIFICATION_TYPES.FRIENDLY_MATCH_CANCELLED]: 'MATCH',
    [NOTIFICATION_TYPES.PLAYER_LEFT_FRIENDLY_MATCH]: 'MATCH',
    [NOTIFICATION_TYPES.SCHEDULING_CONFLICT_DETECTED]: 'MATCH',
    [NOTIFICATION_TYPES.FRIENDLY_MATCH_DETAILS_CHANGED]: 'MATCH',
    [NOTIFICATION_TYPES.MATCH_RESCHEDULE_REQUEST]: 'MATCH',
    [NOTIFICATION_TYPES.MATCH_RESCHEDULE_ACCEPTED]: 'MATCH',
    [NOTIFICATION_TYPES.MATCH_RESCHEDULE_DECLINED]: 'MATCH',
    [NOTIFICATION_TYPES.MATCH_WALKOVER_WON]: 'MATCH',
    [NOTIFICATION_TYPES.MATCH_WALKOVER_LOST]: 'MATCH',
    [NOTIFICATION_TYPES.NO_SHOW_STRIKE_WARNING]: 'MATCH',
    [NOTIFICATION_TYPES.OPPONENT_CLAIMS_NO_SHOW]: 'MATCH',
    [NOTIFICATION_TYPES.HEAD_TO_HEAD_HISTORY]: 'MATCH',
    [NOTIFICATION_TYPES.SCORE_SUBMISSION_REMINDER]: 'MATCH',
    [NOTIFICATION_TYPES.SCORE_DISPUTE_ALERT]: 'MATCH',
    [NOTIFICATION_TYPES.OPPONENT_SUBMITTED_SCORE]: 'MATCH',
    [NOTIFICATION_TYPES.PENDING_SCORE_SUBMISSION]: 'MATCH',
    [NOTIFICATION_TYPES.PENDING_SCORE_CONFIRMATION]: 'MATCH',
    [NOTIFICATION_TYPES.SCORE_AUTO_CONFIRMED]: 'MATCH',
    [NOTIFICATION_TYPES.FORFEIT_DISCIPLINARY]: 'MATCH',

    // Rating & Ranking
    [NOTIFICATION_TYPES.MOVED_UP_IN_STANDINGS]: 'LEAGUE',
    [NOTIFICATION_TYPES.ENTERED_TOP_10]: 'LEAGUE',
    [NOTIFICATION_TYPES.ENTERED_TOP_3]: 'LEAGUE',
    [NOTIFICATION_TYPES.LEAGUE_LEADER]: 'LEAGUE',
    [NOTIFICATION_TYPES.WEEKLY_RANKING_UPDATE]: 'LEAGUE',
    [NOTIFICATION_TYPES.DMR_INCREASED]: 'GENERAL',
    [NOTIFICATION_TYPES.MONTHLY_DMR_RECAP]: 'GENERAL',
    [NOTIFICATION_TYPES.PERSONAL_BEST_RATING]: 'GENERAL',
    [NOTIFICATION_TYPES.RATING_MILESTONE]: 'GENERAL',

    // Social & Community
    [NOTIFICATION_TYPES.FRIEND_ACTIVITY_SCORECARD]: 'CHAT',
    [NOTIFICATION_TYPES.FRIEND_ACTIVITY_POST]: 'CHAT',
    [NOTIFICATION_TYPES.SIMILAR_SKILL_PLAYER_NEARBY]: 'GENERAL',
    [NOTIFICATION_TYPES.SHARE_SCORECARD_PROMPT]: 'GENERAL',
    [NOTIFICATION_TYPES.FRIEND_REQUEST]: 'CHAT',

    // Promotional
    [NOTIFICATION_TYPES.NEXT_SEASON_OPENING_SOON]: 'SEASON',
    [NOTIFICATION_TYPES.SPONSORED_LEAGUE_ANNOUNCEMENT]: 'LEAGUE',
    [NOTIFICATION_TYPES.REFERRAL_BONUS_AVAILABLE]: 'GENERAL',
    [NOTIFICATION_TYPES.INACTIVE_PLAYER_14_DAYS]: 'GENERAL',
    [NOTIFICATION_TYPES.INACTIVE_PLAYER_30_DAYS]: 'GENERAL',
    [NOTIFICATION_TYPES.LEAGUE_BETWEEN_BREAKS]: 'SEASON',
    [NOTIFICATION_TYPES.INCOMPLETE_REGISTRATION]: 'SEASON',
    [NOTIFICATION_TYPES.VENUE_SPECIAL_OFFER]: 'GENERAL',

    // Special Circumstances
    [NOTIFICATION_TYPES.DISPUTE_RESOLUTION_REQUIRED]: 'ADMIN',
    [NOTIFICATION_TYPES.DISPUTE_RESOLVED]: 'ADMIN',
    [NOTIFICATION_TYPES.CODE_OF_CONDUCT_WARNING]: 'ADMIN',
    [NOTIFICATION_TYPES.DISPUTE_SUBMITTED]: 'ADMIN',
    [NOTIFICATION_TYPES.OPPONENT_REPORTED_ISSUE]: 'ADMIN',
  };

  return categoryMap[type] || 'GENERAL';
}